// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://crqkroucckphsbpwflgq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNycWtyb3VjY2twaHNicHdmbGdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0Mzc5MDEsImV4cCI6MjA3MTAxMzkwMX0.Sm1FxejQra2vMnY24bLIPybOv0vqKCn1MBTlAD3fCb8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});